import sys
nl = chr(10)
T = chr(9)

p = 'internal/chaossync/cdt.go'
s = open(p, encoding='utf-8').read()

# добавить импорт time
if '\t"time"\n' not in s:
    s = s.replace('\t"errors"\n', '\t"errors"\n\t"time"\n', 1)

marker = '// --- сторона клиента: фрагментер -------------------------------------------'
idx = s.index(marker)
head = s[:idx]

body = [
'// --- сторона клиента: фрагментер (с ротацией эпох) -------------------------',
'',
'// Fragmenter растворяет поток в запечатанные фрагменты по хаос-геометрии.',
'// Поддерживает ротацию эпох: геометрия и data-ключ мутируют с эпохой хаоса (T),',
'// глобальный seq при этом не сбрасывается — поток непрерывен сквозь ротации.',
'type Fragmenter struct {',
T + 'master  []byte',
T + 'cfg     GeomConfig',
T + 'T       uint64 // сек на эпоху; 0 = фиксированная эпоха (burst/тест)',
T + 'epoch   uint64',
T + 'geom    *GeometrySource',
T + 'aead    cipher.AEAD',
T + 'seq     uint64 // ГЛОБАЛЬНЫЙ порядковый номер (не сбрасывается при ротации)',
T + 'pending []byte',
T + 'cur     PacketGeom',
T + 'hasCur  bool',
'}',
'',
'// NewFragmenter — фиксированная эпоха (burst/тест).',
'func NewFragmenter(master []byte, epoch uint64, cfg GeomConfig) *Fragmenter {',
T + 'return &Fragmenter{master: master, cfg: cfg.withDefaults(), epoch: epoch,',
T + T + 'geom: NewGeometrySource(master, epoch, cfg), aead: cdtDataAEAD(master, epoch)}',
'}',
'',
'// NewRotatingFragmenter — непрерывный туннель: эпоха следует за wall-clock.',
'func NewRotatingFragmenter(master []byte, cfg GeomConfig, T uint64, now time.Time) *Fragmenter {',
T + 'ep := EpochFor(now, T)',
T + 'return &Fragmenter{master: master, cfg: cfg.withDefaults(), T: T, epoch: ep,',
T + T + 'geom: NewGeometrySource(master, ep, cfg), aead: cdtDataAEAD(master, ep)}',
'}',
'',
'// TickEpoch — ротация при смене wall-clock эпохи. Вызывать драйверу по тикеру.',
'func (f *Fragmenter) TickEpoch(now time.Time) {',
T + 'if f.T == 0 {',
T + T + 'return',
T + '}',
T + 'ep := EpochFor(now, f.T)',
T + 'if ep != f.epoch {',
T + T + 'f.epoch = ep',
T + T + 'f.geom = NewGeometrySource(f.master, ep, f.cfg)',
T + T + 'f.aead = cdtDataAEAD(f.master, ep)',
T + T + 'f.hasCur = false // недобранная геометрия сбрасывается при ротации',
T + '}',
'}',
'',
'// Push добавляет payload-байты в буфер на растворение.',
'func (f *Fragmenter) Push(p []byte) { f.pending = append(f.pending, p...) }',
'',
'// Buffered — сколько payload-байт ожидает растворения.',
'func (f *Fragmenter) Buffered() int { return len(f.pending) }',
'',
'// Epoch — текущая эпоха фрагментера.',
'func (f *Fragmenter) Epoch() uint64 { return f.epoch }',
'',
'// Emit — следующий фрагмент. Геометрия расходуется ровно один раз на выпущенный',
'// фрагмент (нода остаётся в ногу). ok=false, если payload меньше хаос-размера —',
'// геометрия при этом НЕ расходуется (та же применится к добивке).',
'func (f *Fragmenter) Emit() ([]byte, PacketGeom, bool) {',
T + 'if !f.hasCur {',
T + T + 'f.cur = f.geom.Next()',
T + T + 'f.hasCur = true',
T + '}',
T + 'g := f.cur',
T + 'if len(f.pending) < g.FragLen {',
T + T + 'return nil, g, false',
T + '}',
T + 'f.hasCur = false',
T + 'chunk := f.pending[:g.FragLen]',
T + 'f.pending = f.pending[g.FragLen:]',
T + 'return f.seal(chunk, g.Nonce), g, true',
'}',
'',
'// EmitFinal — добивка: выдать остаток даже если он меньше хаос-размера.',
'func (f *Fragmenter) EmitFinal() ([]byte, PacketGeom, bool) {',
T + 'if !f.hasCur {',
T + T + 'f.cur = f.geom.Next()',
T + T + 'f.hasCur = true',
T + '}',
T + 'g := f.cur',
T + 'if len(f.pending) == 0 {',
T + T + 'return nil, g, false',
T + '}',
T + 'f.hasCur = false',
T + 'chunk := f.pending',
T + 'f.pending = nil',
T + 'return f.seal(chunk, g.Nonce), g, true',
'}',
'',
'func (f *Fragmenter) seal(chunk []byte, nonce [cdtNonceLen]byte) []byte {',
T + 'plain := make([]byte, cdtSeqLen+len(chunk))',
T + 'binary.BigEndian.PutUint64(plain, f.seq)',
T + 'copy(plain[cdtSeqLen:], chunk)',
T + 'wire := f.aead.Seal(nil, nonce[:], plain, nil)',
T + 'f.seq++',
T + 'out := make([]byte, 0, cdtNonceLen+len(wire))',
T + 'out = append(out, nonce[:]...)',
T + 'out = append(out, wire...)',
T + 'return out',
'}',
'',
'// --- сторона ноды: дефрагментер (с ротацией эпох) --------------------------',
'',
'var (',
T + '// ErrCDTBadFragment — фрагмент не опознан (шум/чужой/повреждён).',
T + 'ErrCDTBadFragment = errors.New("cdt: фрагмент не прошёл AEAD/не из расписания"),',
')',
'',
'// epochSink — контекст одной эпохи: геометрия + data-ключ + окно ожидаемых nonce.',
'type epochSink struct {',
T + 'geom  *GeometrySource',
T + 'aead  cipher.AEAD',
T + 'ahead map[string]struct{} // ожидаемые (ещё не совпавшие) nonce этой эпохи',
T + 'gen   uint64             // сколько nonce сгенерировано',
T + 'used  uint64             // сколько совпало',
'}',
'',
'func newEpochSink(master []byte, epoch uint64, cfg GeomConfig) *epochSink {',
T + 'return &epochSink{',
T + T + 'geom:  NewGeometrySource(master, epoch, cfg),',
T + T + 'aead:  cdtDataAEAD(master, epoch),',
T + T + 'ahead: map[string]struct{}{},',
T + '}',
'}',
'',
'// fill — скользящее окно ожидаемых nonce: держим window впереди поглощённых.',
'func (s *epochSink) fill(window uint64) {',
T + 'for s.gen < s.used+window {',
T + T + 'g := s.geom.Next()',
T + T + 's.ahead[string(g.Nonce[:])] = struct{}{}',
T + T + 's.gen++',
T + '}',
'}',
'',
'// Defragmenter — нода: собирает поток из фрагментов. Знает хаос-узор (та же',
'// GeometrySource на эпоху). Держит текущую и предыдущую эпоху (straddle на',
'// границе). Сборка — по глобальному seq изнутри запечатанного блока, поэтому',
'// поток непрерывен сквозь ротации эпох. Шум/чужие отбрасываются fail-closed.',
'type Defragmenter struct {',
T + 'master  []byte',
T + 'cfg     GeomConfig',
T + 'T       uint64',
T + 'epoch   uint64',
T + 'cur     *epochSink',
T + 'prev    *epochSink',
T + 'deliver uint64 // следующий глобальный seq к выдаче',
T + 'bySeq   map[uint64][]byte',
T + 'ready   [][]byte',
T + 'window  uint64',
'}',
'',
'// NewDefragmenter — фиксированная эпоха (burst/тест).',
'func NewDefragmenter(master []byte, epoch uint64, cfg GeomConfig) *Defragmenter {',
T + 'd := &Defragmenter{master: master, cfg: cfg.withDefaults(), epoch: epoch,',
T + T + 'bySeq: map[uint64][]byte{}, window: 8192}',
T + 'd.cur = newEpochSink(master, epoch, cfg)',
T + 'return d',
'}',
'',
'// NewRotatingDefragmenter — непрерывный туннель: эпоха следует за wall-clock.',
'func NewRotatingDefragmenter(master []byte, cfg GeomConfig, T uint64, now time.Time) *Defragmenter {',
T + 'ep := EpochFor(now, T)',
T + 'd := &Defragmenter{master: master, cfg: cfg.withDefaults(), T: T, epoch: ep,',
T + T + 'bySeq: map[uint64][]byte{}, window: 8192}',
T + 'd.cur = newEpochSink(master, ep, cfg)',
T + 'return d',
'}',
'',
'// TickEpoch — ротация при смене wall-clock эпохи: текущая уходит в prev',
'// (продолжает принимать stragglers с границы), новая становится cur.',
'func (d *Defragmenter) TickEpoch(now time.Time) {',
T + 'if d.T == 0 {',
T + T + 'return',
T + '}',
T + 'ep := EpochFor(now, d.T)',
T + 'if ep != d.epoch {',
T + T + 'd.prev = d.cur',
T + T + 'd.cur = newEpochSink(d.master, ep, d.cfg)',
T + T + 'd.epoch = ep',
T + '}',
'}',
'',
'// Ingest — принять фрагмент с провода. true = опознан и расшифрован.',
'func (d *Defragmenter) Ingest(wire []byte) bool {',
T + 'if len(wire) < cdtNonceLen+cdtSeqLen+16 {',
T + T + 'return false',
T + '}',
T + 'nonce := wire[:cdtNonceLen]',
T + 'ct := wire[cdtNonceLen:]',
T + 'for _, s := range []*epochSink{d.cur, d.prev} {',
T + T + 'if s == nil {',
T + T + T + 'continue',
T + T + '}',
T + T + 's.fill(d.window)',
T + T + 'if _, ok := s.ahead[string(nonce)]; !ok {',
T + T + T + 'continue',
T + T + '}',
T + T + 'plain, err := s.aead.Open(nil, nonce, ct, nil)',
T + T + 'if err != nil {',
T + T + T + 'return false // nonce из расписания, но AEAD не сошёлся — чужой/повреждение',
T + T + '}',
T + T + 'if len(plain) < cdtSeqLen {',
T + T + T + 'return false',
T + T + '}',
T + T + 'gseq := binary.BigEndian.Uint64(plain)',
T + T + 'delete(s.ahead, string(nonce))',
T + T + 's.used++',
T + T + 'd.bySeq[gseq] = plain[cdtSeqLen:]',
T + T + 'd.drain()',
T + T + 'return true',
T + '}',
T + 'return false',
'}',
'',
'func (d *Defragmenter) drain() {',
T + 'for {',
T + T + 'chunk, ok := d.bySeq[d.deliver]',
T + T + 'if !ok {',
T + T + T + 'break',
T + T + '}',
T + T + 'delete(d.bySeq, d.deliver)',
T + T + 'd.ready = append(d.ready, chunk)',
T + T + 'd.deliver++',
T + '}',
'}',
'',
'// Next — следующий по глобальному порядку кусок payload.',
'func (d *Defragmenter) Next() []byte {',
T + 'if len(d.ready) == 0 {',
T + T + 'return nil',
T + '}',
T + 'c := d.ready[0]',
T + 'd.ready = d.ready[1:]',
T + 'return c',
'}',
]

s = head + nl.join(body) + nl
open(p, 'w', encoding='utf-8').write(s)
print('cdt.go: epoch rotation installed')
