import sys
nl = chr(10)
T = chr(9)

p = 'tools/chaossync-lab/main.go'
s = open(p, encoding='utf-8').read()

# 1) case в switch
case_anchor = '\tcase "recon":\n\t\tcmdRecon(os.Args[2:])'
assert case_anchor in s, 'switch anchor'
s = s.replace(case_anchor, case_anchor + nl + '\tcase "multidim":\n\t\tcmdMultidim(os.Args[2:])', 1)

# 2) функции cmdMultidim + genStreamK в конец файла
code = [
'',
'// --- Рычаг 1: многомерное кодирование (гиперхаос, K параллельных драйв-осей) ---',
'//',
'// Замер прироста ёмкости числами на идеальном канале: per-channel BER (cross-talk),',
'// время захвата sync vs K, и честная проверка recon-стойкости — не даёт ли больше',
'// наблюдаемых осей преимущество атакующему (delay-embedding). Мутация (T) — главная',
'// защита; проверяем, что она держится и при K каналах.',
'',
'func cmdMultidim(args []string) {',
T + 'fs := flag.NewFlagSet("multidim", flag.ExitOnError)',
T + 'windows := fs.Int("windows", 3000, "окон измерения BER на канал")',
T + 'syncMax := fs.Int("syncmax", 40000, "макс. сэмплов на захват sync")',
T + '_ = fs.Parse(args)',
T + 'S := 32',
T + 'c := chaossync.MustDecimal("0.85")',
T + 'delta := chaossync.FromRaw(int64(1) << 40) // 2^-8 — дефолтная амплитуда модуляции',
T + 'syncThresh := chaossync.MustDecimal("0.00005")',
T + 'mod := chaossync.Modulator{Delta: delta, S: S}',
T + 'fmt.Println("# Рычаг 1: K параллельных осей в одном хаос-потоке (идеальный канал, loopback)")',
T + 'fmt.Println("K,sync_samples,ber_min,ber_mean,ber_max,recon_stat,recon_mut")',
T + 'for _, K := range []int{1, 2, 3, 4} {',
T + T + 'epoch := uint64(4242)',
T + T + 'field := chaossync.DeriveField(labMaster, epoch)',
T + T + 'drives := chaossync.DeriveDrives(field, K)',
'',
T + T + '// (а) время захвата sync: связь на K сайтов из чужого состояния, без модуляции.',
T + T + 'syncSamples := -1',
T + T + '{',
T + T + T + 'txX := chaossync.EpochInit(labMaster, epoch)',
T + T + T + 'rxX := chaossync.EpochInit(labMaster, epoch+31337)',
T + T + T + 'for i := 0; i < *syncMax; i++ {',
T + T + T + T + 'field.Step(&txX)',
T + T + T + T + 'y := make([]chaossync.Fxp, K)',
T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + 'y[ch] = chaossync.Dequantize16(chaossync.Quantize16(txX[drives[ch]]))',
T + T + T + T + '}',
T + T + T + T + 'r := field.ObserverStepMulti(&rxX, y, c, drives)',
T + T + T + T + 'maxAbs := chaossync.Fxp(0)',
T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + 'if r[ch].Abs() > maxAbs {',
T + T + T + T + T + T + 'maxAbs = r[ch].Abs()',
T + T + T + T + T + '}',
T + T + T + T + '}',
T + T + T + T + 'if maxAbs < syncThresh {',
T + T + T + T + T + 'syncSamples = i',
T + T + T + T + T + 'break',
T + T + T + T + '}',
T + T + T + '}',
T + T + '}',
'',
T + T + '// (б) per-channel BER: K независимых битовых потоков после прогрева.',
T + T + 'ber := make([]float64, K)',
T + T + '{',
T + T + T + 'txX := chaossync.EpochInit(labMaster, epoch)',
T + T + T + 'rxX := chaossync.EpochInit(labMaster, epoch)',
T + T + T + 'for i := 0; i < 2000; i++ { // прогрев до sync',
T + T + T + T + 'field.Step(&txX)',
T + T + T + T + 'y := make([]chaossync.Fxp, K)',
T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + 'y[ch] = chaossync.Dequantize16(chaossync.Quantize16(txX[drives[ch]]))',
T + T + T + T + '}',
T + T + T + T + 'field.ObserverStepMulti(&rxX, y, c, drives)',
T + T + T + '}',
T + T + T + 'rng := rand.New(rand.NewSource(int64(1000 + K)))',
T + T + T + 'errs := make([]int, K)',
T + T + T + 'bits := make([]bool, K)',
T + T + T + 'for w := 0; w < *windows; w++ {',
T + T + T + T + 'for ch := range bits {',
T + T + T + T + T + 'bits[ch] = rng.Intn(2) == 1',
T + T + T + T + '}',
T + T + T + T + 'sumR := make([]chaossync.Fxp, K)',
T + T + T + T + 'for s2 := 0; s2 < S; s2++ {',
T + T + T + T + T + 'field.Step(&txX)',
T + T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + T + 'mod.Perturb(&txX, drives[ch], bits[ch])',
T + T + T + T + T + '}',
T + T + T + T + T + 'y := make([]chaossync.Fxp, K)',
T + T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + T + 'y[ch] = chaossync.Dequantize16(chaossync.Quantize16(txX[drives[ch]]))',
T + T + T + T + T + '}',
T + T + T + T + T + 'r := field.ObserverStepMulti(&rxX, y, c, drives)',
T + T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + T + 'sumR[ch] = sumR[ch].Add(r[ch])',
T + T + T + T + T + '}',
T + T + T + T + '}',
T + T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + T + 'if (sumR[ch] > 0) != bits[ch] {',
T + T + T + T + T + T + 'errs[ch]++',
T + T + T + T + T + '}',
T + T + T + T + '}',
T + T + T + '}',
T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + 'ber[ch] = float64(errs[ch]) / float64(*windows)',
T + T + T + '}',
T + T + '}',
'',
T + T + '// (в) recon-стойкость канала 0: стационарное vs мутирующее поле.',
T + T + 'stat := genStreamK(K, 0, 16000)',
T + T + 'mut := genStreamK(K, 200, 16000)',
T + T + 'nStat := chaossync.ReconNMSEH(stat, 6, 1, 1)',
T + T + 'nMut := chaossync.ReconNMSEH(mut, 6, 1, 1)',
'',
T + T + 'bmin, bmean, bmax := ber[0], 0.0, ber[0]',
T + T + 'for _, b := range ber {',
T + T + T + 'if b < bmin {',
T + T + T + T + 'bmin = b',
T + T + T + '}',
T + T + T + 'if b > bmax {',
T + T + T + T + 'bmax = b',
T + T + T + '}',
T + T + T + 'bmean += b',
T + T + '}',
T + T + 'bmean /= float64(K)',
T + T + 'fmt.Printf("%d,%d,%.5f,%.5f,%.5f,%.4f,%.4f\\n", K, syncSamples, bmin, bmean, bmax, nStat, nMut)',
T + '}',
T + 'fmt.Println("# recon: NMSE<0.1 = реконструкция удалась; прирост ёмкости = xK")',
'}',
'',
'// genStreamK — поток сэмплов наблюдаемого канала 0 в K-канальной системе, где все',
'// K драйв-сайтов пертурбируются независимым PN (реалистичный многоканальный трафик).',
'// T=0 → стационарное поле; T>0 → новая эпоха каждые T сэмплов (мутация).',
'func genStreamK(K, Tt, n int) []uint16 {',
T + 'out := make([]uint16, n)',
T + 'delta := chaossync.FromRaw(int64(1) << 40)',
T + 'mod := chaossync.Modulator{Delta: delta, S: 32}',
T + 'rng := rand.New(rand.NewSource(777))',
T + 'if Tt <= 0 {',
T + T + 'field := chaossync.DeriveField(labMaster, 500)',
T + T + 'drives := chaossync.DeriveDrives(field, K)',
T + T + 'x := chaossync.EpochInit(labMaster, 500)',
T + T + 'for i := range out {',
T + T + T + 'field.Step(&x)',
T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + 'mod.Perturb(&x, drives[ch], rng.Intn(2) == 1)',
T + T + T + '}',
T + T + T + 'out[i] = chaossync.Quantize16(x[drives[0]])',
T + T + '}',
T + T + 'return out',
T + '}',
T + 'for seg := 0; seg*Tt < n; seg++ {',
T + T + 'ep := uint64(9000 + seg)',
T + T + 'field := chaossync.DeriveField(labMaster, ep)',
T + T + 'drives := chaossync.DeriveDrives(field, K)',
T + T + 'x := chaossync.EpochInit(labMaster, ep)',
T + T + 'for i := 0; i < Tt && seg*Tt+i < n; i++ {',
T + T + T + 'field.Step(&x)',
T + T + T + 'for ch := 0; ch < K; ch++ {',
T + T + T + T + 'mod.Perturb(&x, drives[ch], rng.Intn(2) == 1)',
T + T + T + '}',
T + T + T + 'out[seg*Tt+i] = chaossync.Quantize16(x[drives[0]])',
T + T + '}',
T + '}',
T + 'return out',
'}',
]
s = s + nl.join(code) + nl
open(p, 'w', encoding='utf-8').write(s)
print('multidim lab added')
